name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]
        message: [ 'Hello World', 'Lorem Ipsum' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Greetings from ${{ matrix.os }}
      shell: bash
      run: |
        echo "${{ matrix.message }} from ${{ matrix.os }}"